version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: cafe-mongo
    ports:
      - "27017:27017"

  menu:
    build: ./menu-services
    ports:
      - "3001:3001"
    depends_on:
      - mongodb

  order:
    build: ./order-services
    ports:
      - "3002:3002"
    depends_on:
      - mongodb

  inventory:
    build: ./inventory-services
    ports:
      - "3004:3004"
    depends_on:
      - mongodb

  customer:
    build: ./customer-services
    ports:
      - "3005:3005"
    depends_on:
      - mongodb

  gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - menu
      - order
      - inventory
      - customer
